# Generated by Django 4.2.9 on 2026-03-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InsightBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Insight Badge',
                'ordering': ['order', '-count'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_headline', models.CharField(default='Build Smarter. Scale Faster. With AI.', max_length=300)),
                ('hero_subheadline', models.TextField(default='Orchestrix Labs builds production-ready AI systems, voice bots, automation pipelines, and full-stack platforms — engineered to perform from day one.')),
                ('hero_cta_primary', models.CharField(default='See Our Work', max_length=100)),
                ('hero_cta_secondary', models.CharField(default='Start a Project', max_length=100)),
                ('about_headline', models.CharField(default='We turn complex problems into intelligent software.', max_length=300)),
                ('about_story', models.TextField(blank=True, default='', help_text='Main about page narrative. Supports paragraphs separated by newlines.')),
                ('about_values', models.JSONField(blank=True, default=list, help_text='List of {title, description} objects')),
                ('contact_email', models.EmailField(default='contact@orchestrixlabs.com', max_length=254)),
                ('contact_linkedin', models.URLField(blank=True, default='', max_length=500)),
                ('contact_github', models.URLField(blank=True, default='', max_length=500)),
                ('contact_upwork', models.URLField(blank=True, default='', max_length=500)),
                ('services_headline', models.CharField(default='Everything you need to build an intelligent business.', max_length=300)),
                ('services_data', models.JSONField(blank=True, default=list, help_text='Full services array [{id, title, tagline, description, features, tools, color, accent}]')),
                ('process_steps', models.JSONField(blank=True, default=list, help_text='Process steps [{step, title, description}]')),
                ('site_name', models.CharField(default='Orchestrix Labs', max_length=100)),
                ('site_tagline', models.CharField(default='AI-Powered Software Development Agency', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_role', models.CharField(blank=True, default='', max_length=150)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('quote', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='Upwork', max_length=50)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
