# Generated by Django 4.2.9 on 2026-03-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('discussion', 'Discussion'), ('in_progress', 'In Progress'), ('started_work', 'Started Work'), ('completed', 'Completed'), ('archived', 'Archived')], default='new', max_length=20),
        ),
    ]
