from django.core.management.base import BaseCommand
from portfolio.models import Project

PROJECTS = [
    {
        'order': 1,
        'title': 'Restaurant Order Management — Voice AI',
        'category': 'Voice AI & Chatbots',
        'summary': 'Full-stack restaurant system with voice-based order processing, real-time kitchen display, thermal printing and SMS notifications.',
        'description': 'Developed a comprehensive restaurant order management system integrating SynthFlow voice AI, PrintNode cloud printing, Supabase real-time subscriptions, and Twilio SMS — all in a single production-ready platform.',
        'tech': ['React', 'FastAPI', 'Supabase', 'Twilio', 'OpenAI', 'SynthFlow', 'PrintNode', 'AWS EC2'],
        'highlights': [
            'Voice order processing via SynthFlow webhooks with AI-powered parsing',
            'ESC/POS thermal printer support with Chinese character rendering',
            'Real-time Kitchen Display System (KDS) with color-coded status',
            'Multi-tenant architecture — onboard new restaurants in minutes',
        ],
        'impact': ['95% reduction in order entry errors', 'Real-time kitchen visibility', 'Automated customer SMS notifications', 'Multi-restaurant scalability'],
        'featured': True,
    },
    {
        'order': 2,
        'title': 'Launch Vector — AI Voice Lead Qualification',
        'category': 'Voice AI & Chatbots',
        'summary': 'End-to-end AI voice pipeline that auto-qualifies leads and books meetings the moment a HubSpot form is submitted.',
        'description': 'Built a complete AI Voice Agent pipeline connecting HubSpot, SynthFlow.ai, and HubSpot Meetings API. The system triggers intelligent outbound calls instantly on form submission, qualifies leads, and books calendar meetings automatically.',
        'tech': ['Python', 'SynthFlow.ai', 'HubSpot API', 'Webhooks', 'FastAPI'],
        'highlights': [
            'Instant webhook-triggered outbound AI calls on lead form submission',
            'Lead qualification by budget threshold (≥$100k liquid capital)',
            'Real-time calendar availability fetch and auto-booking',
            'Full TCPA/DNC compliance with voicemail detection and SMS fallback',
        ],
        'impact': ['Response time reduced from hours to seconds', 'Full HubSpot audit trail', 'Higher meeting booking conversion', 'Zero manual follow-up needed'],
        'featured': True,
    },
    {
        'order': 3,
        'title': 'AI HR Assistant — Bilingual Multi-Agent System',
        'category': 'Voice AI & Chatbots',
        'summary': 'Bilingual (Arabic + English) AI assistant for HR operations with RAG pipeline, deep email/calendar integration and document management.',
        'description': 'Built a fully customized multi-agent AI HR assistant powered by GPT-4 and LangChain. The system integrates Gmail, Outlook, Google Calendar, Google Drive and MS Office — grounded in company data via a FAISS vector database.',
        'tech': ['OpenAI GPT-4', 'LangChain', 'FAISS', 'Gmail API', 'Google Calendar', 'Outlook API', 'Google Drive', 'Python'],
        'highlights': [
            'Multi-agent architecture with specialized HR, KPI and productivity agents',
            'RAG pipeline searching HR manuals, KPI sheets, labor law references',
            'Full bilingual Arabic + English support',
            'Auto-drafts emails, schedules meetings, generates documents',
        ],
        'impact': ['80% improvement in HR policy accuracy', 'Automated document generation', '60% reduction in routine HR task time'],
        'featured': True,
    },
    {
        'order': 4,
        'title': 'Emma — AI Voice Receptionist (Condo Management)',
        'category': 'Voice AI & Chatbots',
        'summary': 'Voice-powered AI receptionist handling real-time inbound calls for a condo management platform using Twilio and GPT-4.',
        'description': 'Built and deployed Emma, integrating Twilio Programmable Voice with GPT-4 to handle live tenant calls, answer property queries, and log transcripts to Supabase. Fallback to voicemail/human if AI cannot resolve the query.',
        'tech': ['Twilio Voice', 'GPT-4', 'Supabase', 'React', 'FastAPI', 'Webhooks'],
        'highlights': [
            'Real-time AI conversation with minimal latency',
            'Webhook architecture for prompt voice interaction',
            'Call transcript logging and analytics dashboard',
            'Human handoff fallback for unresolved queries',
        ],
        'impact': ['24/7 tenant support', '70% reduction in call center workload', 'Full call history and analytics'],
        'featured': False,
    },
    {
        'order': 5,
        'title': 'Tammy — AI Voice Receptionist (ExecConnect)',
        'category': 'Voice AI & Chatbots',
        'summary': 'Retell.ai + Twilio voice bot with Outlook Calendar booking, Airtable CRM logging and Azure-hosted FastAPI backend.',
        'description': 'Developed Tammy for ExecConnect — a professional AI receptionist integrating Retell.ai via Twilio trunk, GPT-4 function calling for calendar booking, and Airtable as CRM. Hosted on Azure App Service.',
        'tech': ['Retell.ai', 'Twilio', 'GPT-4', 'FastAPI', 'Azure', 'Outlook Calendar', 'Microsoft Graph API', 'Airtable', 'React'],
        'highlights': [
            'Twilio + Retell.ai professional voice trunk setup',
            'GPT-4 function calling for real-time calendar availability and booking',
            'Airtable CRM integration for full lead and call logging',
            'Warm persona design with intelligent voicemail/human fallback',
        ],
        'impact': ['Automated appointment scheduling', '24/7 client inquiry handling', 'Complete lead tracking pipeline'],
        'featured': False,
    },
    {
        'order': 6,
        'title': 'RAG Psychiatrist Assistant',
        'category': 'Machine Learning & AI',
        'summary': 'Private AI assistant for psychiatrists with local FAISS vector DB, semantic search over PDFs/Word docs, and GPT-4 answers.',
        'description': 'Built a secure, offline-capable AI assistant allowing psychiatrists to upload clinical documents and query them with semantic search. Combines private RAG context with GPT-4 general knowledge for hybrid, grounded answers.',
        'tech': ['OpenAI GPT-4', 'LangChain', 'FAISS', 'FastAPI', 'PyMuPDF', 'Python'],
        'highlights': [
            'Local FAISS vector database for secure, offline document storage',
            'Supports PDF, Word, and plain-text document ingestion',
            'Hybrid answers: private context + GPT-4 general knowledge',
            'FastAPI backend with clean RESTful endpoints',
        ],
        'impact': ['Reduced document search time drastically', 'Enhanced clinical decision support', 'Secure, fully local document management'],
        'featured': True,
    },
    {
        'order': 7,
        'title': 'Custom Image Background Removal — ML Pipeline',
        'category': 'Machine Learning & AI',
        'summary': 'U-2-Net deep learning pipeline for batch background removal of 10,000+ irregularly shaped rug images with 95%+ accuracy.',
        'description': 'Developed a custom Python ML pipeline using a fine-tuned U-2-Net model to segment and remove backgrounds from thousands of top-down rug images. Fully offline, batch-processing script with smooth edge post-processing.',
        'tech': ['Python', 'PyTorch', 'U-2-Net', 'OpenCV', 'NumPy', 'Pillow'],
        'highlights': [
            'Custom U-2-Net model for irregular salient object detection',
            'OpenCV preprocessing for noise reduction and edge enhancement',
            'RGBA transparent output with smooth edge blending',
            'Batch processing with folder input/output support',
        ],
        'impact': ['95%+ background removal accuracy', '10,000+ images processed', '90% reduction in processing time', 'Eliminated all manual masking'],
        'featured': False,
    },
    {
        'order': 8,
        'title': 'Matify Studio — AI Image Generation Platform',
        'category': 'Machine Learning & AI',
        'summary': 'Full-stack AI platform for custom model training, image generation, outfit swap, face retouch, background removal and upscaling.',
        'description': 'Built a complete AI-powered image generation SaaS with Django backend and React frontend. Users train custom AI models via Replicate API, generate images, and apply advanced editing tools. Features a credit-based usage system and AWS S3 storage.',
        'tech': ['Django', 'React', 'Tailwind CSS', 'Replicate API', 'AWS S3', 'PostgreSQL'],
        'highlights': [
            'Custom AI model training via Replicate API',
            'Real-time image generation with trained models',
            'Outfit swap, face retouch, background removal, upscaling tools',
            'Credit-based system with user authentication',
        ],
        'impact': ['5,000+ images generated in live deployment', 'Scalable credit billing system', 'Production-ready SaaS platform'],
        'featured': True,
    },
    {
        'order': 9,
        'title': 'MCA Master Data Scraper — 2,400 Companies',
        'category': 'Web Scraping & Automation',
        'summary': 'Automated scraper extracting MCA master data for 2,400 Indian companies with CAPTCHA handling, proxy rotation and structured CSV export.',
        'description': 'Built a robust Python scraper to navigate the MCA portal, handle CAPTCHA/anti-bot checks, and extract complete company master data including CIN, director details, registration info, and compliance data for 2,400+ companies.',
        'tech': ['Python', 'Selenium', 'Playwright', 'BeautifulSoup', 'Pandas'],
        'highlights': [
            'Automated CAPTCHA handling and anti-bot bypass',
            'Proxy rotation and request throttling',
            'Batch processing with retry and error handling',
            'Clean CSV/Excel export for analysis',
        ],
        'impact': ['2,400+ company records extracted', 'Hundreds of hours of manual work saved', 'Structured data ready for analysis'],
        'featured': False,
    },
    {
        'order': 10,
        'title': 'LinkedIn Sales Navigator Auto-Filler Bot',
        'category': 'Web Scraping & Automation',
        'summary': 'Selenium bot that reads company URLs from CSV and auto-adds them to a specified Sales Navigator list with real-time status tracking.',
        'description': 'Built a browser automation bot that opens each LinkedIn company profile from a CSV, navigates to Sales Navigator, and saves the account into a user-specified list. Includes full CLI interface, error handling, and status logging.',
        'tech': ['Python', 'Selenium', 'ChromeDriver', 'Pandas', 'OpenPyXL'],
        'highlights': [
            'CLI interface with dynamic list name input',
            'CSV/XLS company URL ingestion',
            'Automated Sales Navigator profile navigation and saving',
            'Real-time success/failure logging',
        ],
        'impact': ['Eliminated hours of repetitive clicking', 'Scalable for large company lists', 'Reduced human error to near zero'],
        'featured': False,
    },
    {
        'order': 11,
        'title': 'Google Maps Data Scraper — Clinics & Buildings',
        'category': 'Web Scraping & Automation',
        'summary': 'Google Places API scraper to extract and categorize clinics and residential buildings within custom geolocations for urban planning.',
        'description': 'Developed a Python scraper using the Google Places API and Reverse Geocoding to extract names, categories, addresses, and coordinates for clinics and residential buildings within user-defined geographic areas.',
        'tech': ['Python', 'Google Maps Places API', 'Google Geocoding API', 'Requests', 'Pandas'],
        'highlights': [
            'Geolocation-based extraction with custom radius support',
            'Category differentiation: clinics, hospitals, residential',
            'API quota optimization and pagination handling',
            'Clean CSV output ready for mapping or analytics',
        ],
        'impact': ['Thousands of location records extracted', 'Enabled data-driven urban planning', 'Supported healthcare resource distribution analysis'],
        'featured': False,
    },
    {
        'order': 12,
        'title': 'Helium 10 Automated CSV Downloader',
        'category': 'Web Scraping & Automation',
        'summary': 'Headless Selenium script automating authenticated login and batch CSV downloads from Helium 10, integrated with Microsoft Power Automate.',
        'description': 'Created a Python automation script to log into Helium 10, navigate authenticated dashboard pages, and download multiple structured CSV files with unique timestamps. Integrated with Power Automate for downstream file handling.',
        'tech': ['Python', 'Selenium', 'Requests', 'dotenv', 'Microsoft Power Automate'],
        'highlights': [
            'Headless authenticated browser session management',
            'Batch file downloads with timestamp naming',
            'Power Automate trigger integration',
            'Retry logic and download confirmation checks',
        ],
        'impact': ['Eliminated repetitive manual downloads', 'Automated BI reporting pipeline', 'Reduced manual errors completely'],
        'featured': False,
    },
    {
        'order': 13,
        'title': 'TPC America — Django E-commerce & Data Pipeline',
        'category': 'Full-Stack Development',
        'summary': 'Large-scale Django e-commerce upgrade with scraped product ingestion, ETL pipeline, PostgreSQL schema design, and REST APIs.',
        'description': 'Upgraded and expanded a Django-based e-commerce site for TPC America, building scraping pipelines to ingest thousands of products from supplier websites, designing the PostgreSQL schema, and exposing REST APIs for frontend consumption.',
        'tech': ['Python', 'Django', 'PostgreSQL', 'Scrapy', 'BeautifulSoup', 'Django REST Framework', 'Celery'],
        'highlights': [
            'Custom PostgreSQL schema for complex product categories and variants',
            'Scrapy + BeautifulSoup multi-vendor product scrapers',
            'Celery-based async ETL pipeline with data validation',
            'Extended Django admin for bulk management and filtering',
        ],
        'impact': ['Thousands of product records integrated', 'Automated data collection pipeline', 'Improved search and filtering capabilities'],
        'featured': True,
    },
    {
        'order': 14,
        'title': 'VBScript Desktop App → Python Flask Web Migration',
        'category': 'Full-Stack Development',
        'summary': 'Full rewrite of a legacy VBScript desktop app into a modern Flask web app with MySQL, payments, Dropbox, HR modules, and MFA.',
        'description': 'Rewrote an entire legacy VBScript desktop application into a modern Flask web platform, migrating from MSSQL to MySQL, integrating Dropbox API, payment gateways (SnapScan, Zapper, PayFast), and deploying securely on DigitalOcean with MFA.',
        'tech': ['Python', 'Flask', 'MySQL', 'Dropbox API', 'PayFast', 'SnapScan', 'Zapper', 'DigitalOcean'],
        'highlights': [
            'Complete legacy-to-modern migration with UI/UX parity',
            'MSSQL → MySQL data migration with full data integrity',
            'Multi-payment gateway integration (SnapScan, Zapper, PayFast)',
            'Deployed with MFA, Nginx, and SSL on DigitalOcean',
        ],
        'impact': ['Modernized inaccessible desktop app to web', 'Enhanced security with MFA', 'Maintained 100% user familiarity'],
        'featured': False,
    },
    {
        'order': 15,
        'title': 'AI Email Assistant — n8n + OpenAI + Google Sheets',
        'category': 'Workflow Automation',
        'summary': 'Automated email management system: GPT-4 summarizes emails, drafts replies, logs to Google Sheets, and notifies via Notion/Slack.',
        'description': 'Built an n8n workflow that triggers on new Gmail messages, uses GPT-4 to summarize and draft replies, logs all data to Google Sheets, and optionally notifies via Notion or Slack — eliminating email overload for busy professionals.',
        'tech': ['n8n', 'Gmail API', 'OpenAI GPT-4', 'Google Sheets API', 'Notion API', 'Slack API'],
        'highlights': [
            'Gmail trigger filtered by label or keyword',
            'GPT-4 2-line summarization and reply drafting',
            'Auto-send or draft-save configurable per client',
            'Full email audit trail in Google Sheets',
        ],
        'impact': ['Automated daily email management', 'Faster response times', 'Zero inbox overload'],
        'featured': False,
    },
    {
        'order': 16,
        'title': 'Data Entry Automation for ASP.NET Systems',
        'category': 'Workflow Automation',
        'summary': 'Selenium + Zapier automation pipeline extracting invoice data and injecting it into secured internal ASP.NET web apps.',
        'description': 'Built automated workflows using Selenium bots and Zapier to extract data from invoices and digital forms, then inject it into ASP.NET internal systems — replacing dozens of hours of weekly manual data entry.',
        'tech': ['Python', 'Selenium', 'Zapier', 'Google Forms', 'JotForm', 'OCR', 'HTML Parsing'],
        'highlights': [
            'Selenium WebDriver for ASP.NET multi-page form simulation',
            'JotForm/Google Forms integration via Zapier',
            'Dynamic field mapping and multi-page form navigation',
            'OCR support for scanned document ingestion',
        ],
        'impact': ['Dozens of hours saved weekly', 'Automated across multiple ASP.NET modules', 'Near-zero data entry errors'],
        'featured': False,
    },
    {
        'order': 17,
        'title': 'Outbound Call Center & Auto-Dialer — Twilio',
        'category': 'Voice AI & Chatbots',
        'summary': 'Full-featured outbound call center platform with Twilio auto-dialer, agent dashboard, call recording, and real-time analytics.',
        'description': 'Built a production-grade outbound call center system with Twilio Programmable Voice. Features an auto-dialer that cycles through lead lists, a live agent dashboard with call controls, call recording, voicemail drop, and a management admin panel with campaign analytics.',
        'tech': ['Python', 'FastAPI', 'Twilio', 'React', 'PostgreSQL', 'WebSockets'],
        'highlights': [
            'Twilio-powered auto-dialer with configurable call pacing',
            'Live agent dashboard with real-time call controls',
            'Voicemail drop and automated follow-up scheduling',
            'Campaign analytics and call recording management',
        ],
        'impact': ['Eliminated manual dialing entirely', 'Real-time campaign performance visibility', 'Scalable multi-agent architecture'],
        'featured': True,
    },
    {
        'order': 18,
        'title': 'Omni-channel AI Support Bot',
        'category': 'Voice AI & Chatbots',
        'summary': 'Unified AI chatbot handling customer support across multiple channels (web, SMS, email) with GPT-4 and seamless agent handoff.',
        'description': 'Developed an omni-channel bot integrating GPT-4 to handle customer queries across web chat, SMS (Twilio), and email simultaneously. Features context preservation across channels, smart escalation to live agents, and full conversation history logging.',
        'tech': ['Python', 'OpenAI GPT-4', 'Twilio', 'FastAPI', 'React', 'PostgreSQL'],
        'highlights': [
            'Unified context across web chat, SMS, and email channels',
            'GPT-4 powered natural language understanding',
            'Smart escalation triggers for live agent handoff',
            'Full conversation history and analytics dashboard',
        ],
        'impact': ['Automated multi-channel support 24/7', 'Consistent customer experience across platforms', 'Reduced support ticket volume significantly'],
        'featured': False,
    },
    {
        'order': 19,
        'title': 'Text-to-CAD AI Generator',
        'category': 'Machine Learning & AI',
        'summary': 'AI system that converts natural language descriptions into 3D CAD models using GPT-4 and parametric design APIs.',
        'description': 'Built an innovative AI pipeline that takes plain English descriptions of mechanical parts or structures and generates corresponding 3D CAD models. Combines GPT-4 for intent parsing with parametric CAD generation APIs to output industry-standard file formats.',
        'tech': ['Python', 'OpenAI GPT-4', 'FastAPI', 'CAD APIs', 'React'],
        'highlights': [
            'Natural language to CAD parameter extraction via GPT-4',
            'Parametric 3D model generation from text descriptions',
            'Industry-standard CAD file format export',
            'Interactive refinement with iterative prompt support',
        ],
        'impact': ['Eliminated manual CAD drafting for standard parts', 'Accelerated prototyping workflow', 'Opened CAD access to non-technical users'],
        'featured': True,
    },
    {
        'order': 20,
        'title': 'DreamBooth Auto Fine-tuning Pipeline',
        'category': 'Machine Learning & AI',
        'summary': 'Automated Stable Diffusion fine-tuning system using DreamBooth with custom training pipelines, prompt engineering, and batch image generation.',
        'description': 'Developed an automated DreamBooth fine-tuning system allowing users to train custom Stable Diffusion models on their own images. Built end-to-end: training data prep, GPU-accelerated model training, prompt engineering, and batch inference with quality filtering.',
        'tech': ['Python', 'PyTorch', 'Stable Diffusion', 'DreamBooth', 'CUDA', 'Hugging Face'],
        'highlights': [
            'End-to-end automated DreamBooth training pipeline',
            'Custom image dataset preprocessing and augmentation',
            'GPU-accelerated training with checkpoint management',
            'Batch inference with automated quality scoring',
        ],
        'impact': ['59 hours of custom AI model fine-tuning delivered', '5.0 Upwork rating', 'Production-ready personalized image generation'],
        'featured': False,
    },
    {
        'order': 21,
        'title': 'Company Lead Scraper — Names, Domains & Emails',
        'category': 'Web Scraping & Automation',
        'summary': 'Long-running scraper (207 hours) extracting company names, domains, and verified emails at scale for B2B lead generation.',
        'description': 'Built and maintained a large-scale lead generation scraper over 207 hours that extracts company names, website domains, and verified email addresses from multiple sources. Includes email validation, deduplication, and structured CSV/database export pipelines.',
        'tech': ['Python', 'Playwright', 'BeautifulSoup', 'Requests', 'Pandas', 'PostgreSQL'],
        'highlights': [
            'Multi-source company and domain extraction pipeline',
            'Email verification and validation layer',
            'Deduplication and data normalization at scale',
            'Automated scheduling and incremental update support',
        ],
        'impact': ['$4,133 engagement over 207 hours', '5.0 Upwork rating', 'Thousands of verified B2B leads delivered', 'Ongoing long-term client relationship'],
        'featured': False,
    },
    {
        'order': 22,
        'title': 'Enterprise Web Scraper — 221-Hour Engagement',
        'category': 'Web Scraping & Automation',
        'summary': 'Complex long-term scraping project for an enterprise client extracting structured data from a dynamic, auth-protected website over 221 hours.',
        'description': 'Delivered one of the largest scraping engagements on record — a 221-hour project building a robust, maintainable scraper for an enterprise client. Handled authentication, session management, anti-bot countermeasures, data normalization, and continuous delivery of structured data.',
        'tech': ['Python', 'Selenium', 'Playwright', 'BeautifulSoup', 'Pandas', 'PostgreSQL'],
        'highlights': [
            'Auth-protected session management with auto-refresh',
            'Anti-bot countermeasure bypass with stealth techniques',
            'Incremental data extraction with change detection',
            'Structured database storage with full audit trail',
        ],
        'impact': ['$5,249 — largest scraping engagement', '5.0 Upwork rating', '"True expert in his field. Delivers on time."', '221 hours of sustained delivery'],
        'featured': True,
    },
    {
        'order': 23,
        'title': 'Government & Public Register Scraper',
        'category': 'Web Scraping & Automation',
        'summary': 'Multi-source scraper extracting structured data from government and public online registers over 130 hours for regulatory research.',
        'description': 'Built a comprehensive scraping system targeting multiple government portals and public online registers. Handled diverse anti-bot measures, dynamic JavaScript rendering, CAPTCHA bypass, and normalized outputs across inconsistent data schemas.',
        'tech': ['Python', 'Playwright', 'Selenium', 'BeautifulSoup', 'Pandas', 'OCR'],
        'highlights': [
            'Multi-portal extraction with unified data schema',
            'JavaScript-rendered page handling via Playwright',
            'CAPTCHA solving and session persistence',
            'Automated data normalization across inconsistent formats',
        ],
        'impact': ['$3,258 engagement over 130 hours', '5.0 Upwork rating', 'Complete regulatory dataset delivered', 'Enabled large-scale compliance research'],
        'featured': False,
    },
    {
        'order': 24,
        'title': 'WeddingWire Vendor Data Scraper',
        'category': 'Web Scraping & Automation',
        'summary': 'Full-scale WeddingWire scraper extracting vendor profiles, ratings, reviews, contact info, and pricing across categories and geographies.',
        'description': 'Built a targeted scraper for WeddingWire to extract complete vendor data including business names, categories, locations, ratings, review counts, contact information, and pricing details. Delivered clean, analysis-ready dataset.',
        'tech': ['Python', 'Playwright', 'BeautifulSoup', 'Pandas', 'PostgreSQL'],
        'highlights': [
            'Category and geography-based pagination handling',
            'Full vendor profile extraction including reviews',
            'Anti-bot evasion with rate limiting and randomization',
            'Clean CSV + database export for analysis',
        ],
        'impact': ['5.0 Upwork rating — "Excellent to work with, highly recommended"', 'Thousands of vendor records delivered', 'Market research dataset for wedding industry analytics'],
        'featured': False,
    },
]


class Command(BaseCommand):
    help = 'Seed the database with all 24 portfolio projects'

    def add_arguments(self, parser):
        parser.add_argument('--clear', action='store_true', help='Clear existing projects before seeding')

    def handle(self, *args, **options):
        if options['clear']:
            count = Project.objects.count()
            Project.objects.all().delete()
            self.stdout.write(self.style.WARNING(f'Deleted {count} existing projects.'))

        created = 0
        updated = 0
        for data in PROJECTS:
            obj, was_created = Project.objects.update_or_create(
                order=data['order'],
                defaults=data,
            )
            if was_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(self.style.SUCCESS(
            f'Done. {created} projects created, {updated} updated. Total: {Project.objects.count()}'
        ))
