# Generated by Django 4.2.9 on 2026-03-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Voice AI & Chatbots', 'Voice AI & Chatbots'), ('Machine Learning & AI', 'Machine Learning & AI'), ('Web Scraping & Automation', 'Web Scraping & Automation'), ('Full-Stack Development', 'Full-Stack Development'), ('Workflow Automation', 'Workflow Automation')], db_index=True, max_length=100)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('tech', models.JSONField(default=list)),
                ('highlights', models.JSONField(default=list)),
                ('impact', models.JSONField(default=list)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', 'id'],
            },
        ),
    ]
